### PR TITLE
interface opengl based rendering from sispo

### PR DESCRIPTION
**Pull request by oknuutti**
I interfaced opengl based rendering from sispo (activate by using `--opengl` argument), made sispo runnable from command line with e.g. `python -m sispo -i data/input/definition_opengl.json`, moved camera model specific code from compositor to sc.Instrument.sense so that can use it from opengl rendering code. I skipped the compositor for as stars are rendered on my side (for now) and the opengl renderer gives (at least should give) out calibrated fluxes. In future, sispo star rendering code could be used, no problem. The default camera model from sispo is used, but some other could be used also, including my own.

I tested with `data/input/definition_opengl.json` but could not test yet with `data/input/definition.json` as I couldn't get blender related dependencies to work yet. Could someone try out both input files and check that results seem ok?

To be able to use the opengl based render, you need to install the dependencies by using
```
pip install numpy-quaternion
pip install git+https://github.com/oknuutti/visnav-py.git#egg=visnav
```

### CODE REVIEW

**Comment by oknuutti** [comment]
Ah, the .obj & .mtl files that `data/input/definition_opengl.json` uses can be downloaded from [here](https://drive.google.com/open?id=1j7-zz5LkWvEZWyYiVPPn5oHWxe-nr1nA) and [here](https://drive.google.com/open?id=18O2VV3O78BNeG5_OVjdJyDZS9rv-mOUF) and they should go to `data/models`

**Comment by oknuutti** [comment]
What was the error message when you tried `python -m sispo`? From where were you trying to run it? Shell/command prompt, right? Were you at the project root where the `data`, `doc`, `sispo`, `software`, etc folders are?
I'm not certain I understand what you mean with running the main() inside the sispo.py in the main part.

I moved the camera/instrument specific code from the compositor to a specific `sense` method of the Instrument class so that it can be used for the flux/irradiance images originating from both blender and the opengl renderer.

**Comment by YgabrielsY** [comment]
Yes, I was running it from the project root, but python wasn't able to find all the module dependencies.
I refer to the `if __name__ == "__main__":` part in the `sispo.py`. Anyway, I'll merge it so you can continue, maybe I'll give it a look again to refactor it. I personally would prefer if it's possible to avoid the `__main__.py` solution.

Ah ok, now I get, then this is fine.

**Comment by oknuutti** [comment]
Cool, about the __main__.py, it's needed so that can run the code with the `-m` switch (run module), the `__name__=='__main__'` in sispo.py would work if running in script mode (`python sispo/sispo.py`). However, somehow I couldn't get it to work, it was complaining something about the imports. If you manage to get the imports to work, then I think the script mode would be preferrable.

**Pull request merged**
